import { ThemeProvider } from '@/components/theme-provider';

import type { Metadata } from 'next';
import { Source_Code_Pro } from 'next/font/google';

import './globals.css';

const scp = Source_Code_Pro({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Hans' blog",
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={scp.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
